### PR TITLE
Fix broken nested collections with custom prototype names

### LINKED ISSUE #1014: Nested collection is broken
Commit 89344f914155a7bcf805cf5354bd3ad208a94f11 broke prototype replacement in nested collection.

### PR DESCRIPTION
**Pull request by molchanoviv**
Fixes #1014

### CODE REVIEW

**Comment by molchanoviv** [comment]
@phiamo @piotrantosik Updated.

**Comment by piotrantosik** [comment]
:+1: work perfectly

**Comment by phiamo** [comment]
Mhh nice.. Will try merging this evening
Am 27.01.2015 13:30 schrieb "Piotr Antosik" <notifications@github.com>:

**Comment by phiamo** [comment]
tnx!

**Pull request merged**
