### PR TITLE
Added parameter 'with_remove_icon' to date, time, datetime fields.

### PR DESCRIPTION
**Pull request by nnmer**
This allow to add remove button to date/time/datetime widget and remove values from input field

### CODE REVIEW

**Comment by phiamo** [comment]
@nnmer can you add documentation and use case please

**Comment by nnmer** [comment]
Documentation:

```
->add('birthday',null,array(
                'widget' => 'single_text',
                'datepicker' => true,
                'with_remove_icon' => true
            ))
```

by adding to configuration:
```
'with_remove_icon' => true
```

we will get:
with_x

If we do not add this parameter to field configuration, we will get only:
without_x

Without reset ("x") button we cannot set field to null;

**Comment by isometriks** [comment]
Can we use the `widget_addon` block here to keep the code DRY? I think some other instances could be replaced with this as well. Also, can't we just use the widget_addon_append here to do this? Do we really need to introduce another variable?

**Comment by nnmer** [comment]
I agree to keep things more simple.


I just tried 
```
->add('birthday',null,array(
                'widget' => 'single_text',
                'datepicker' => true,
                'widget_addon_append' => ['icon'=>'remove']
))
```
it adding the remove button to the field, but 'calendar' icon not created.


Actually, this can be counted as a bug, that addon append replace probably existing addon, as in datetime widget. If we can fix that, probably this should affect only datetime widget, then yes, just keep using already builtin functionality

**Comment by nnmer** [comment]
or let me know how to append, if it is possible without the replacing. I cannot find it myself.

**Comment by nnmer** [comment]
Closing this, temporary will use my fork to get remove date button work

**Pull request closed without merging**
