### PR TITLE
[WIP] Add badges to Menus

### PR DESCRIPTION
**Pull request by jonny827**
Fix Issue #1169 .

@isometriks will you please assist me in figuring out what else needs to be done here so this can be merged?

### CODE REVIEW

**Comment by isometriks** [comment]
I think you should probably use the macro from views/macros.html.twig for the badges. I would say pass false to the use_raw and add a badge_class with default value false, and pass to the macro so you can change the type of badge. 

Also, please squash your commits when done so it's just one in the PR.

**Comment by isometriks** [comment]
Sorry, use "badge-class" for consistency.

**Comment by jonny827** [comment]
@isometriks I think the administrator of the repository has to squash commits upon merge now.  I do not see a way to do this. Please advise if I have missed something.  This is the information I read [here](https://github.com/blog/2141-squash-your-commits).

**Comment by isometriks** [comment]
Sorry, I had meant to add an option to the menu extension so you can pass the badge class you want. 

    $menu->add('foo', array (
        'badge' => 5,
        'badge-class' => 'info',
    ));

You can squash your commits locally with "rebase -i master" then only pick one commit and squash the rest. Then force push your branch

**Comment by jonny827** [comment]
I.  have tried every option in Windows PHPSTORM with no result,  
2. Already lost my entire menu builder class when something froze when trying to test your requested bage-class modification. 
3. Is it that hard to squash on merge?  I tried to rebase/rebase github fork everything through options and nothing.

**Comment by isometriks** [comment]
Awesome, thank you!

**Pull request merged**
