### PR TITLE
Fontawesome fonts paths fixed

### PR DESCRIPTION
**Pull request by cluster28**

### CODE REVIEW

**Comment by cluster28** [comment]
Forget this pull request

**Comment by jonny827** [comment]
@cluster28 Can you update this Pull Request to implement Font Awesome 4.7 please. We might as well suppose the latest library available. I was going to make a PR myself but I see yours is already in the works.

**Comment by phiamo** [comment]
@cluster28 ping

**Comment by cluster28** [comment]
@jonny827 @phiamo Done only for less

**Comment by cluster28** [comment]
@phiamo ping

**Comment by isometriks** [comment]
Is FontAwesome BC? Will this introduce any issues to anyone? 

I'll merge it if this is an issue, but I'll repeat my sentiment again for anyone else who may find this issue: Manage your assets separately. Don't use them from the bundle, you will end up stuck using an old version, or new version etc. Add them to your AppBundle or use NPM or whatever package manager. They were planned to be removed but I don't know how the activity on this bundle will continue with symfony supporting lots of bootstrap stuff natively.

**Pull request closed without merging**
