### PR TITLE
added compatibility with label_format

### PR DESCRIPTION
**Pull request by mrcmorales**
added compatibility with feature #12050 [Form] Added "label_format" option (webmozart)

https://github.com/symfony/symfony/commit/832c78f47df9ecef08171ec375c712d5b064427a

### CODE REVIEW

**Comment by phiamo** [comment]
@mrcmorales can you add documentation for this please

**Comment by mrcmorales** [comment]
@phiamo I can, but this feature is from symfony, then this doc would be in symfony doc.

This doc are done in symfony doc but not merge yet.

https://github.com/symfony/symfony-docs/pull/4412

**Comment by phiamo** [comment]
ah, did this come with a recent version of symfony? do we need a version constraint, i assume no, you tried to come over this as far as i understand the PR. if thats true i am fine merging this

**Comment by mrcmorales** [comment]
This feature was added in 2.6

http://symfony.com/blog/a-week-of-symfony-405-29-september-05-october-2014
https://github.com/symfony/symfony/pull/12050

**Comment by isometriks** [comment]
Will we need an `and is defined label_format`? as well for previous versions of Symfony since this variable won't be defined?

**Comment by phiamo** [comment]
Not sure if the is emty does the trick, but yes thats what i mesnt too. Can smbd confirm this?

**Comment by mrcmorales** [comment]
@phiamo to be secure, I can add label_format is defined condition.

**Comment by mrcmorales** [comment]
@phiamo I tested with sf 2.3 and is necessary control if var is defined, I updated PR.

**Comment by phiamo** [comment]
thanks a lot

**Pull request merged**
