### PR TITLE
Refactored deprecations of latest symfony and twig releases

### PR DESCRIPTION
**Pull request by peterrehm**
I did some small refactorings to update to comply with Symfony 2.7 and the upcoming Twig 2.0 release and to avoid the deprecation warnings.

It would be great if this could be merged and a new release could be created.

### CODE REVIEW

**Comment by peterrehm** [comment]
Any oppinion on that?

**Comment by isometriks** [comment]
I think we'd like to keep support for 2.3 right now so you would need to keep setDefaultOptions and call configureOptions from it as 2.3 is still supported for a while as was done in some of the form types

**Comment by peterrehm** [comment]
That is still the case on previous releases... I am just considering if I will continue to work on this on this repo or just on my fork.

**Comment by phiamo** [comment]
i would be pleased if we could merge this once ! thanks a lot!

**Comment by peterrehm** [comment]
Closing this PR as there has not been activity. If anyone needs functionality for 2.7 / 2.8 I did some additional work here: https://github.com/peterrehm/MopaBootstrapBundle/tree/pr2.3.x

**Comment by isometriks** [comment]
I would merge it of you didn't remove support for 2.3, it needs the BC layer of setDefaultOptions to call configureOptions. We can think about targeting 2.7 or 2.8+ for 4.0

**Pull request closed without merging**
