### PR TITLE
menu: append classes instead of overwriting them when using 'dropdown' option

### PR DESCRIPTION
**Pull request by tulanowski**
to solve problem https://github.com/phiamo/MopaBootstrapBundle/issues/1058

### CODE REVIEW

**Comment by phiamo** [comment]
not sure if it will break bc, but it should only for prople already setting this variable, so we should consider adding more logic like not setting it at all if items class is explicitly set to false, and preventing ouble adding dropdown class. could you add that to this pr?

**Comment by tulanowski** [comment]
Well.. yes, it is some BC break - classes on 'dropdown' items will no longer be removed, but that's the point - in my opinion it is sane default behaviour. Moreover it is already possible to set 'dropdown' option to false, to skip this whole dropdown related logic. My current workaround relies on that - set 'dropdown' option to false, and all items classes set manually.

**Comment by phiamo** [comment]
ah yeah i see if options[dropdown] false dont do anything, could you add some docs to this PR please, then i assume it might be sane to merge @isometriks any further comments?

**Comment by isometriks** [comment]
Yeah I think this is fine to merge, it _could_ be BC but I wouldn't think there would be many side effects from this. :+1:

**Pull request merged**
