### PR TITLE
Collection entry options

### PR DESCRIPTION
**Pull request by MisatoTremor**
Enable overriding collection entry options from the collection options.

### CODE REVIEW

**Comment by phiamo** [comment]
@MisatoTremor ping again :-)

**Comment by MisatoTremor** [comment]
I've looked into this again and this PR is obsolete.
It's function is already implemented with the 'options' option in the collection form type from Symfony.
The problem why it does not work is the condition
```twig
{% set show_horizontal_wrapper = horizontal and not (form.parent is not null and 'collection' in form.parent.vars.block_prefixes) %}
```
like @svscorp mentioned in #805.

It seems it was [added](622aebb) so the form widget of a collection item isn't wrapped in the default wrappers. This is good if the collection item is a sub form, but hinders having a custom wrapper.

@phiamo: How about adding the ``horizontal_wrap_children`` option to the collection type extension, defaulting to false and changing above line to
```twig
{% set show_horizontal_wrapper = horizontal and not (form.parent is not null and 'collection' in form.parent.vars.block_prefixes and form.parent.vars.horizontal_wrap_children is sameas(false)) %}
```
This way, the default behavior stays as is and configured children wrapper classes take effect.

If OK, I'd open a new PR with that option and a sandbox PR with some samples.

**Comment by phiamo** [comment]
sounds very good, thanks for investigating on this. i you could add a pr here and one for the sandbox, that would be awesome, probably we this might also have todo with #1014 not sure

**Comment by isometriks** [comment]
Shouldn't we be able to grab the wrapper meant for the children if you do something like this?

```php
$builder->add('something', 'collection', array(
    'options' => array(
        'horizontal...' => 'whatever',
    ),
));
```

It should work this way anyway, since that options should be passed to all child forms of the collection if I'm remembering how forms work correctly. If this doesn't work, this is how it should work. I don't think there's a need to introduce a new option. Let me know if I'm wrong though, I didn't put much time into looking into this.

**Comment by MisatoTremor** [comment]
Yes, like mentioned you can already override these options on the childs with the ``options`` option of the collection items. But they will simply not be used because of the condition in twig a collection child item is never wrapped.
Also you can't use these options (``horizontal...``) in the condition as they are always set with their default value in ``HorizontalFormTypeExtension``.

**Comment by MisatoTremor** [comment]
New PR #1028 added, also added sandbox PR

**Pull request closed without merging**
