### PR TITLE
Fix crash on rendering prototype for collectionType

### PR DESCRIPTION
**Pull request by Legenyes**
Since bump to Symfony 5.1 rendering form with macro generate crash.

> _An exception has been thrown during the rendering of a template ("Field "\__name\__" has already been rendered, save the result of previous render call to a variable and output that instead.")._

See the TwigBridge commit : [[TwigBridge][Form] Prevent multiple rendering of form collection prototype](https://github.com/symfony/twig-bridge/commit/d44fd94cd060f03b28c9db500b80e1fb88d5ebec)

```
    {% macro childPrototype(item) %}
	{{ form(item.quantity) }}
    {% endmacro %}

    {% import _self as macro %}
    {% block content %}
	<script id="childPrototype" type="text/html">
		{{ macro.childPrototype(form.items.vars.prototype) }}
	</script>

	{% for key, item in form.items %}
		{{ macro.childPrototype(item) }}
	{% endfor %}
    {% endbblock %}
```

### CODE REVIEW

**Comment by deguif** [comment]
@Legenyes could you rebase your branch with master, now that CI is green.

**Comment by Legenyes** [comment]
@deguif I do it

**Comment by deguif** [comment]
Thank you @Legenyes

**Comment by Legenyes** [comment]
@deguif  Is there a new tag / release planned?

**Comment by deguif** [comment]
@Legenyes I just release v3.4.1. Enjoy ;)

**Pull request merged**
