### PR TITLE
Support Symfony 7

### PR DESCRIPTION
**Pull request by op-euga**

### CODE REVIEW

**Comment by op-euga** [comment]
is there anything to do from my side? I think you just need to approve, and hopefully make a release.

**Comment by vasanth-kumar-m-y** [comment]
@phiamo please approve and merge this PR
@op-euga

**Comment by phiamo** [comment]
thanks a lot

**Comment by op-euga** [comment]
when will there be a release with this?

**Comment by phiamo** [comment]
thanks for the hint, right now

**Pull request merged**
