### PR TITLE
Improve true/false/null default values on configuration

### PR DESCRIPTION
**Pull request by Soullivaneuh**

### CODE REVIEW

**Comment by phiamo** [comment]
thanks a lot! i think this could be a BC but it should have been done years ago! @isometriks i think we want to merge this asap no?

**Comment by Soullivaneuh** [comment]
> i think this could be a BC

Why do you think that?

**Comment by phiamo** [comment]
mhh cause i think we have had probs due to these not set values, and maybe people rely on them beeing NULL so this could be a BC in these cases, but i think also it would be good to have them as you proposed!

**Comment by phiamo** [comment]
shit i misread the diff, everything fine

**Comment by phiamo** [comment]
sry :-)

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
