### PR TITLE
Add option to enable collection child horizontal wrapping

### PR DESCRIPTION
**Pull request by MisatoTremor**
| Q             | A
| ------------- | ---
| Replaces | #907
| Sandbox PR | phiamo/MopaBootstrapSandboxBundle#42

### CODE REVIEW

**Comment by phiamo** [comment]
bildschirmfoto von 2015-01-26 15 34 09

this doesnt look so good :( any idea why?

**Comment by phiamo** [comment]
```
<div class="col-sm-9">
   <div class="form-group collection-items mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_form_group" data-prototype="<div  class=&quot;collection-item&quot;><div class=&quot;input-group&quot;><span class=&quot;input-group-addon&quot;>@</span><input type=&quot;email&quot; id=&quot;mopa_bootstrap_example_collections_forms_nice_email_collection_with_options___name__&quot; name=&quot;mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][__name__]&quot; required=&quot;required&quot; class=&quot;form-control&quot; /></div><div class=&quot;col-lg-4&quot;><a  class=&quot;btn btn-default&quot; data-collection-remove-btn=&quot;.mopa_bootstrap_example_collections_forms_nice_email_collection_with_options___name___form_group&quot;><span class=&quot;glyphicon glyphicon-trash&quot;></span>
      remove
      </a></div></div>" data-prototype-name="__name__" data-prototype-label="__name__label__" id="collectionmopa_bootstrap_example_collections_forms_nice_email_collection_with_options_form_group">
      <div class="collection-item">
         <div class="col-lg-8 ">
            <div class="input-group"><span class="input-group-addon">@</span><input type="email" id="mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_0" name="mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][0]" required="required" class="form-control" value="some@other.com"></div>
         </div>
         <div class="col-lg-4"><a class="btn btn-default" data-collection-remove-btn=".mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_0_form_group"><span class="glyphicon glyphicon-trash"></span>
            remove
            </a>
         </div>
      </div>
      <div class="collection-item">
         <div class="col-lg-8 ">
            <div class="input-group"><span class="input-group-addon">@</span><input type="email" id="mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_1" name="mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][1]" required="required" class="form-control" value="phiamo@googlemail.com"></div>
         </div>
         <div class="col-lg-4"><a class="btn btn-default" data-collection-remove-btn=".mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_1_form_group"><span class="glyphicon glyphicon-trash"></span>
            remove
            </a>
         </div>
      </div>
      <div class="collection-item">
         <div class="input-group"><span class="input-group-addon">@</span><input type="email" id="mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_3" name="mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][3]" required="required" class="form-control"></div>
         <div class="col-lg-4"><a class="btn btn-default" data-collection-remove-btn=".mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_3_form_group"><span class="glyphicon glyphicon-trash"></span>
            remove
            </a>
         </div>
      </div>
      <div class="collection-item">
         <div class="input-group"><span class="input-group-addon">@</span><input type="email" id="mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_4" name="mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][4]" required="required" class="form-control"></div>
         <div class="col-lg-4"><a class="btn btn-default" data-collection-remove-btn=".mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_4_form_group"><span class="glyphicon glyphicon-trash"></span>
            remove
            </a>
         </div>
      </div>
      <div class="collection-item">
         <div class="input-group"><span class="input-group-addon">@</span><input type="email" id="mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_5" name="mopa_bootstrap_example_collections_forms[nice_email_collection_with_options][5]" required="required" class="form-control"></div>
         <div class="col-lg-4"><a class="btn btn-default" data-collection-remove-btn=".mopa_bootstrap_example_collections_forms_nice_email_collection_with_options_5_form_group"><span class="glyphicon glyphicon-trash"></span>
            remove
            </a>
         </div>
      </div>
   </div>
</div>
```

thats the html generated

**Comment by MisatoTremor** [comment]
Sorry, I missed setting the ``horizontal`` option in the sandbox PR. I've added a commit to that PR.

**Comment by phiamo** [comment]
np ! thanks for checking! i hope today i will find time again :/

**Pull request merged**
