### PR TITLE
borrowed travis yml from foshttpcache lets see if it makes travis happy,...

### PR DESCRIPTION
**Pull request by phiamo**
... or if it even runs

### CODE REVIEW

**Comment by isometriks** [comment]
Yeah, there's no easy way I can see to get this to work on 2.7 without changing setDefaultOptions to configureOptions, or disabling warnings (which isn't a great idea as we might miss other warnings, but I guess exceptions are more important). Maybe we should only target up to 2.6 right now and then create another branch that works for 2.7+ as it will be LTS.

**Comment by phiamo** [comment]
yep thats what i tried here, but i will give the solution from @dbu https://github.com/FriendsOfSymfony/FOSHttpCacheBundle/commit/f227d42640d5e8bee64ec3ecbcefb0068cd32886#commitcomment-9378532 a chance :-)

**Comment by dbu** [comment]
the reason this does not work is that you have no file Tests/bootstrap.php 
as you directly use vendor/autoload.php you can use that in the second `echo >> ` thing on that horrible line of bash you copied from me :-)

**Comment by phiamo** [comment]
ahhhh i seee

**Comment by MisatoTremor** [comment]
I also think it would be nice to have a branch for symfony 2.7 or even sync branches to symfony / use existing as needed (currently 2.3, 2.6, 2.7 and master for 3.0).
As a possible  versioning scheme - to maintain compatibility with the existing (and legacy) branches - I propose ``BOOTSTRAP_MAJOR.SYMFONY_MAJOR.SYMFONY_MINOR`` e.g. ``3.2.3``, ``3.2.6``, ... (``3.3.0`` when Symfony begins the 3.0 branch) - with the possible addon of a fourth level for Mopa internal bugfix releases (composer supports 4 levels for semantic versioning).

**Comment by phiamo** [comment]
@Soullivaneuh fixed this recently so i can close that obe

**Pull request closed without merging**
